# Generated by Django 5.0.1 on 2025-04-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktransaction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
    ]
