# Generated by Django 5.0.1 on 2025-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0002_booktransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
