# Generated by Django 5.0.1 on 2025-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0003_booktransaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
