# Generated by Django 5.0.1 on 2025-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0004_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
