# Generated by Django 5.0.1 on 2025-04-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0007_bookcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_book',
            field=models.BooleanField(default=False),
        ),
    ]
